name: Docker

on:
  push:
    branches: [ "main" ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: kyrylrs/csca-front


jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository:  ${{ env.IMAGE_NAME }}
          tags: latest
